repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: grafana
    url: https://grafana.github.io/helm-charts

releases:
  - name: prometheus
    chart: prometheus-community/prometheus
    values:
      - ./charts/prometheus/values.yaml

  - name: grafana
    chart: grafana/grafana
    values:
      - ./charts/grafana/values.yaml

  - name: alertmanager
    chart: prometheus-community/alertmanager
    values:
      - ./charts/alertmanager/values.yaml

  - name: loki
    chart: grafana/loki
    values:
      - ./charts/loki/values.yaml
