apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-secret
  labels:
    app: alertmanager
type: Opaque
data:
  auth_username: {{ .Values.config.receivers[0].email_configs[0].auth_username | b64enc | quote }}
  auth_password: {{ .Values.config.receivers[0].email_configs[0].auth_password | b64enc | quote }}
